
Complete installation:
======================

Enable GG replication:
======================

show parameter enable_goldengate_replication
Alter system set enable_goldengate_replication=true scope=spfile sid='*';;

Alter database ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE FORCE LOGGING;

SELECT SUPPLEMENTAL_LOG_DATA_MIN, FORCE_LOGGING FROM V$DATABASE;

CREATE USERS and tablespace:
=============================

## for PDB create user starting with prefix C## to connect with container:
========================================================================

create tablespace gg_data datafile '+DATA' size 500M;
create user C##ggadmin identified by password default tablespace gg_data temporary tablespace temp;
alter user C##ggadmin quota unlimited on gg_data ;
grant connect,resource,dba to C##ggadmin;
EXEC DBMS_GOLDENGATE_AUTH.GRANT_ADMIN_PRIVILEGE(grantee => 'C##ggadmin', privilege_type => '*',  grant_select_privileges=> true, do_grants => TRUE);
GRANT SELECT ON V_$DATABASE TO C##ggadmin;

create another user for replicat inside pdb:
==============================================

alter session set container=<PDB>;
create tablespace gg_data datafile '+DATA' size 500M;
create user ggadmin identified by password default tablespace gg_data temporary tablespace temp;
alter user ggadmin quota unlimited on gg_data ;
grant connect,resource,dba to ggadmin;
EXEC DBMS_GOLDENGATE_AUTH.GRANT_ADMIN_PRIVILEGE(grantee => 'ggadmin', privilege_type => '*',  grant_select_privileges=> true, do_grants => TRUE);
GRANT SELECT ON V_$DATABASE TO ggadmin;

create tablespace INSISHIST datafile '+DATA' size 10G;
create user insishist identified by InsisHistUAT1234 default tablespace INSISHIST temporary tablespace temp;
alter user insishist quota unlimited on INSISHIST ;
grant connect,resource to insishist;

## for standalone:
===================
create tablespace gg_data datafile '+DATA' size 500M;
create user ggadmin identified by password default tablespace gg_data temporary tablespace temp;
alter user ggadmin quota unlimited on gg_data ;
grant connect,resource,dba to ggadmin;
EXEC DBMS_GOLDENGATE_AUTH.GRANT_ADMIN_PRIVILEGE(grantee => 'ggadmin', privilege_type => '*',  grant_select_privileges=> true, do_grants => TRUE);
GRANT SELECT ON V_$DATABASE TO ggadmin;

create tablespace INSISHIST datafile '+DATA' size 10G;
create user insishist identified by InsisHistUAT1234 default tablespace INSISHIST temporary tablespace temp;
alter user insishist quota unlimited on INSISHIST ;
grant connect,resource to insishist;


Create Database credential wallet:
===================================
Create Wallet
Add CredentialStore
Alter CredentialStore Add User C##ggadmin@<container_DB> Password password Alias oggcdbadmin
Alter CredentialStore Add User ggadmin@<PDB> Password password Alias oggpdbadmin
Info CredentialStore
DBLogin UserIDAlias oggcdbadmin
ADD CHECKPOINTTABLE GGADMIN.gg_checkpoint
ADD HEARTBEATTABLE

Copy the parameter files in dirprm location:
=============================================
1.INEDW.prm
2.INRDW.prm
3.mgr.prm
4.defgen.prm

in PDB make sure below parameter is added in INEDW.prm file.

SOURCECATALOG <PDB_NAME>

create extract and replicat:
============================
DBLogin UserIDAlias oggcdbadmin
register extract INEDW database  ==> save the scn number at this point
add extract INEDW, INTEGRATED tranlog, begin now
ADD EXTTRAIL <GG_HOME>/dirdat/ie, EXTRACT INEDW

DBLogin UserIDAlias oggpdbadmin
add replicat INRDW INTEGRATED exttrail <GG_HOME>/dirdat/ie
exit


Create metadata for HIST tables:
====================================

Two ways to create metadat, first to copy metadata from other ens or use hist_metadata_creation.sql

take export from UPGSIT:
========================
expdp \"/ as sysdba\" content=METADATA_ONLY directory=EXPORT dumpfile=INSISHIST.dmp logfile=INSISHIST_export.log VERSION=19.0.0 schemas=INSISHIST
 
" 
import into PDB:
==================
impdp system/<password>@<PDB> directory=EXPDIR_YAMUNA dumpfile=INSISHIST.dmp logfile=INSISHIST_export_import.log 

verify it should complete with no errors.

initial load:
==============
start extract process and capture SCN from database at the same time.Make sure extract is starting and running without any issues.

col current_scn for 999999999999999999;
select current_scn from v$database;

use this scn number in below export command:

export for initial load:
=========================
expdp  system/InScdBpaSsWrDsyS64@INDUS directory=EXPDIR_DIR dumpfile=GG_Tables.dmp flashback_scn=<scn> tables=INSIS_CUST.CUST_CLM_HANDLERS,INSIS_CUST.POLICY_LABEL,INSIS_CUST.P_PROPERTY,INSIS_CUST.P_PROPERTY_ADDRESS,INSIS_CUST.P_PROPERTY_BUILDING,INSIS_CUST.RISK_CODES_MAPPING,INSIS_GEN_BLC_V10.BLC_DOCUMENTS,INSIS_GEN_BLC_V10.BLC_INSTALLMENTS,INSIS_GEN_CFG_V10.CFG_NL_COVER_RULES,INSIS_GEN_CFG_V10.CFG_NL_COVERS,INSIS_GEN_CFG_V10.CFG_NL_COVER_TEXT,INSIS_GEN_CFG_V10.CFG_NL_OBJECT_RULES,INSIS_GEN_CFG_V10.CFG_NL_OBJECTS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_LAYERS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_PARAMS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_REPATTR,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_RULES,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_TEXT,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_VERSIONS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_VERSIONS_LAYERS,INSIS_GEN_CFG_V10.CPR_COVER,INSIS_GEN_CFG_V10.CPR_DISCOUNTS,INSIS_GEN_CFG_V10.CPR_ENDORSEMENT,INSIS_GEN_CFG_V10.CPR_LAYER,INSIS_GEN_CFG_V10.CPR_OBJECTS,INSIS_GEN_CFG_V10.CPR_PARAMS,INSIS_GEN_CFG_V10.CPR_RULES,INSIS_GEN_CFG_V10.CPRS_COVER_RISKS,INSIS_GEN_CFG_V10.CPRS_DISCOUNTS,INSIS_GEN_CFG_V10.CPRS_ENDORSEMENT,INSIS_GEN_CFG_V10.CPRS_PARAM_VALUE,INSIS_GEN_CFG_V10.CPRS_RULE_DEFINITION,INSIS_GEN_CFG_V10.SYSCFG_CLAIM_EVENTS,INSIS_GEN_CFG_V10.SYSCFG_PRODUCT_STATUS,INSIS_GEN_CFG_V10.SYSCFG_TRANSLATIONS,INSIS_GEN_V10.BLC_CLAIM,INSIS_GEN_V10.BLC_POLICY_PAYMENT_PLAN,INSIS_GEN_V10.CLAIM,INSIS_GEN_V10.CLAIM_CATASTROPHIC_EVENT,INSIS_GEN_V10.CLAIM_DOCLAD_BENEF_LIST,INSIS_GEN_V10.CLAIM_EXPENSES,INSIS_GEN_V10.CLAIM_OBJECTS,INSIS_GEN_V10.CLAIM_OBJECTS_DSCR_FRACT,INSIS_GEN_V10.CLAIM_PARTICIPANTS,INSIS_GEN_V10.CLAIM_PAYMENTS,INSIS_GEN_V10.CLAIM_PAYMENTS_DETAILS,INSIS_GEN_V10.CLAIM_REFUSES,INSIS_GEN_V10.CLAIM_REGRESSES,INSIS_GEN_V10.CLAIM_REGRESSES_SUM,INSIS_GEN_V10.CLAIM_REQUEST,INSIS_GEN_V10.CLAIM_RESERVE_HISTORY,INSIS_GEN_V10.GEN_ANNEX,INSIS_GEN_V10.GEN_ANNEX_REASON,INSIS_GEN_V10.GEN_PREMIUM_TAXES,INSIS_GEN_V10.GEN_RESERVE_CLAIM,INSIS_GEN_V10.GEN_RESERVE_CORP,INSIS_GEN_V10.GEN_RISK_COVERED,INSIS_GEN_V10.GEN_RISK_DISCOUNT,INSIS_GEN_V10.GEN_RISK_INDEMNITY,INSIS_GEN_V10.GEN_RISK_RISKS,INSIS_GEN_V10.HST_CLAIM_STATE,INSIS_GEN_V10.HST_ENG_POLICY_TYPE,INSIS_GEN_V10.HST_OBJECT_TYPE,INSIS_GEN_V10.HT_ANNEX_REASON,INSIS_GEN_V10.HT_CLAIM_CATASTROPHIC_EVENTS,INSIS_GEN_V10.HT_CLAIM_REFUSE,INSIS_GEN_V10.INSURED_OBJECT,INSIS_GEN_V10.O_ACCINSURED,INSIS_GEN_V10.O_PROPERTY,INSIS_GEN_V10.O_SHIP,INSIS_GEN_V10.POLICY,INSIS_GEN_V10.POLICY_AGENTS,INSIS_GEN_V10.POLICY_ALTERATIONS,INSIS_GEN_V10.POLICY_ANNEX,INSIS_GEN_V10.POLICY_CONDITIONS,INSIS_GEN_V10.POLICY_ENDORSEMENTS,INSIS_GEN_V10.POLICY_ENGAGEMENT_BILLING,INSIS_GEN_V10.POLICY_PARTICIPANTS,INSIS_GEN_V10.POLICY_RENEWAL,INSIS_GEN_V10.PREM_INST_DISC,INSIS_GEN_V10.PREM_INST_INTERIM,INSIS_GEN_V10.PREM_INST_WP,INSIS_PEOPLE_V10.P_AGENTS,INSIS_PEOPLE_V10.P_CLIENTS,INSIS_PEOPLE_V10.P_OFFICES,INSIS_PEOPLE_V10.P_PEOPLE,INSIS_PEOPLE_V10.P_STAFF,INSIS_PEOPLE_V10.P_USER_ACCOUNTS,INSIS_SYS_V10.CFG_NOM_LANGUAGE_TABLE,INSIS_SYS_V10.DOC_DOCUMENTS,INSIS_SYS_V10.QUEST_QUESTIONS,INSIS_GEN_V10.CLAIM_DOCLAD,INSIS_GEN_BLC_V10.BLC_TRANSACTIONS,INSIS_GEN_BLC_V10.BLC_APPLICATIONS,INSIS_GEN_V10.BLC_CLAIM_FRACT,INSIS_GEN_BLC_V10.BLC_PAYMENTS,INSIS_GEN_BLC_V10.BLC_PAY_INSTRUMENTS,INSIS_GEN_V10.HST_PAYMENT_MODE,INSIS_GEN_V10.HST_PAYMENT_WAY,INSIS_CUST.CUST_CLAIM_PAYMENT_REQUEST,INSIS_CUST.CUST_CLAIM_PAYMENT_REQUEST_DET,INSIS_CPX_V10.HT_CLAIM_DIAGNOSIS_TYPE,INSIS_NTW_V10.CFG_COVER_DIAGNOSIS,INSIS_NTW_V10.HT_DIAGNOSIS_GROUP_CATEGORY,INSIS_NTW_V10.HT_DIAGNOSIS,INSIS_NTW_V10.HT_DIAGNOSIS_GROUPS,INSIS_NTW_V10.CFG_DIAGNOSIS_GROUPS,INSIS_NTW_V10.HT_DIAGNOSIS_TYPE,INSIS_SYS_V10.PSDA_STEPS,INSIS_SYS_V10.PSDA_STEP_VALUES,INSIS_GEN_V10.CLAIM_INSPECTIONS    logfile=GG_Tables_exp.log 


Change SRC_COMMIT_TS to older value for existing records:
===========================================================

ALTER TABLE INSISHIST.IC_CUSTCLMHANDLERS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IC_PPROPERTY MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGBV_BLCDOCUMENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGBV_BLCINSTALLMENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLCOVERRULES MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLCOVERTEXT MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLCOVERS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLOBJECTRULES MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLOBJECTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCT MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTLAYERS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTPARAMS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTREPATTR MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTRULES MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTTEXT MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTVERSIONS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTVERSIONSLAYER MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRCOVER MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRDISCOUNTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRENDORSEMENT MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRLAYER MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPROBJECTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRPARAMS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRRULES MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRSCOVERRISKS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRSDISCOUNTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRSENDORSEMENT MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRSPARAMVALUE MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_CPRSRULEDEFINITION MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_SYSCFGCLAIMEVENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_SYSCFGPRODUCTSTATUS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGCV_SYSCFGTRANSLATIONS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_BLCCLAIM MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_BLCPOLICYPAYMENTPLAN MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIM MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMCATASTROPHICEVENT MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMDOCLADBENEFLIST MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMEXPENSES MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMOBJECTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMOBJECTSDSCRFRACT MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMPARTICIPANTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMPAYMENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMPAYMENTSDETAILS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMREFUSES MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMREGRESSES MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMREGRESSESSUM MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMREQUEST MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMRESERVEHISTORY MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_GENANNEX MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_GENANNEXREASON MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_GENPREMIUMTAXES MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_GENRESERVECLAIM MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_GENRESERVECORP MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_GENRISKCOVERED MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_GENRISKDISCOUNT MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_GENRISKINDEMNITY MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_GENRISKRISKS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_HSTCLAIMSTATE MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_HSTENGPOLICYTYPE MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_HSTOBJECTTYPE MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_HTANNEXREASON MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_HTCLAIMCATASTROPHICEVENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_HTCLAIMREFUSE MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_INSUREDOBJECT MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_OACCINSURED MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_OPROPERTY MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_OSHIP MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_POLICY MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_POLICYAGENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_POLICYALTERATIONS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_POLICYANNEX MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_POLICYCONDITIONS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_POLICYENDORSEMENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_POLICYENGAGEMENTBILLING MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_POLICYPARTICIPANTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_POLICYRENEWAL MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_PREMINSTDISC MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_PREMINSTINTERIM MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_PREMINSTWP MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IPV_PAGENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IPV_PCLIENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IPV_POFFICES MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IPV_PPEOPLE MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IPV_PSTAFF MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IPV_PUSERACCOUNTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.ISV_CFGNOMLANGUAGETABLE MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.ISV_DOCDOCUMENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.ISV_QUESTQUESTIONS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IC_PPROPERTYADDRESS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IC_PPROPERTYBUILDING MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IC_RISKCODESMAPPING MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IC_POLICYLABEL MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIMDOCLAD MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGBV_BLCTRANSACTIONS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGBV_BLCAPPLICATIONS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_BLCCLAIMFRACT MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGBV_BLCPAYMENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGBV_BLCPAYINSTRUMENTS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_HSTPAYMENTMODE MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_HSTPAYMENTWAY MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IC_CUSTCLAIMPAYMENT_REQUEST MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IC_CUSTCLM_PAYMENT_REQ_DET MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.ICV_HTCLAIM_DIAGNOSISTYPE MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.INV_CFGCOVERDIAGNOSIS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.INV_HTDIAGNOSIS_GROUPCATEGORY MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.INV_HTDIAGNOSIS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.INV_HTDIAGNOSISGROUPS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.INV_CFGDIAGNOSISGROUPS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.INV_HTDIAGNOSISTYPE MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.ISV_PSDASTEPS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.ISV_PSDASTEPVALUES MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');
ALTER TABLE INSISHIST.IGV_CLAIM_INSPECTIONS MODIFY SRC_COMMIT_TS DEFAULT to_date('1753-01-01','YYYY-MM-DD');

import tables into INSISHIST by remapping schema and table : 
============================================================

impdp system/InScdBpaSsWrDsyS64@INDUS directory=EXPDIR_DIR tables=INSIS_CUST.CUST_CLM_HANDLERS,INSIS_CUST.POLICY_LABEL,INSIS_CUST.P_PROPERTY,INSIS_CUST.P_PROPERTY_ADDRESS,INSIS_CUST.P_PROPERTY_BUILDING,INSIS_CUST.RISK_CODES_MAPPING,INSIS_GEN_BLC_V10.BLC_DOCUMENTS,INSIS_GEN_BLC_V10.BLC_INSTALLMENTS,INSIS_GEN_CFG_V10.CFG_NL_COVER_RULES,INSIS_GEN_CFG_V10.CFG_NL_COVERS,INSIS_GEN_CFG_V10.CFG_NL_COVER_TEXT,INSIS_GEN_CFG_V10.CFG_NL_OBJECT_RULES,INSIS_GEN_CFG_V10.CFG_NL_OBJECTS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_LAYERS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_PARAMS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_REPATTR,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_RULES,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_TEXT,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_VERSIONS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_VERSIONS_LAYERS,INSIS_GEN_CFG_V10.CPR_COVER,INSIS_GEN_CFG_V10.CPR_DISCOUNTS,INSIS_GEN_CFG_V10.CPR_ENDORSEMENT,INSIS_GEN_CFG_V10.CPR_LAYER,INSIS_GEN_CFG_V10.CPR_OBJECTS,INSIS_GEN_CFG_V10.CPR_PARAMS,INSIS_GEN_CFG_V10.CPR_RULES,INSIS_GEN_CFG_V10.CPRS_COVER_RISKS,INSIS_GEN_CFG_V10.CPRS_DISCOUNTS,INSIS_GEN_CFG_V10.CPRS_ENDORSEMENT,INSIS_GEN_CFG_V10.CPRS_PARAM_VALUE,INSIS_GEN_CFG_V10.CPRS_RULE_DEFINITION,INSIS_GEN_CFG_V10.SYSCFG_CLAIM_EVENTS,INSIS_GEN_CFG_V10.SYSCFG_PRODUCT_STATUS,INSIS_GEN_CFG_V10.SYSCFG_TRANSLATIONS,INSIS_GEN_V10.BLC_CLAIM,INSIS_GEN_V10.BLC_POLICY_PAYMENT_PLAN,INSIS_GEN_V10.CLAIM,INSIS_GEN_V10.CLAIM_CATASTROPHIC_EVENT,INSIS_GEN_V10.CLAIM_DOCLAD_BENEF_LIST,INSIS_GEN_V10.CLAIM_EXPENSES,INSIS_GEN_V10.CLAIM_OBJECTS,INSIS_GEN_V10.CLAIM_OBJECTS_DSCR_FRACT,INSIS_GEN_V10.CLAIM_PARTICIPANTS,INSIS_GEN_V10.CLAIM_PAYMENTS,INSIS_GEN_V10.CLAIM_PAYMENTS_DETAILS,INSIS_GEN_V10.CLAIM_REFUSES,INSIS_GEN_V10.CLAIM_REGRESSES,INSIS_GEN_V10.CLAIM_REGRESSES_SUM,INSIS_GEN_V10.CLAIM_REQUEST,INSIS_GEN_V10.CLAIM_RESERVE_HISTORY,INSIS_GEN_V10.GEN_ANNEX,INSIS_GEN_V10.GEN_ANNEX_REASON,INSIS_GEN_V10.GEN_PREMIUM_TAXES,INSIS_GEN_V10.GEN_RESERVE_CLAIM,INSIS_GEN_V10.GEN_RESERVE_CORP,INSIS_GEN_V10.GEN_RISK_COVERED,INSIS_GEN_V10.GEN_RISK_DISCOUNT,INSIS_GEN_V10.GEN_RISK_INDEMNITY,INSIS_GEN_V10.GEN_RISK_RISKS,INSIS_GEN_V10.HST_CLAIM_STATE,INSIS_GEN_V10.HST_ENG_POLICY_TYPE,INSIS_GEN_V10.HST_OBJECT_TYPE,INSIS_GEN_V10.HT_ANNEX_REASON,INSIS_GEN_V10.HT_CLAIM_CATASTROPHIC_EVENTS,INSIS_GEN_V10.HT_CLAIM_REFUSE,INSIS_GEN_V10.INSURED_OBJECT,INSIS_GEN_V10.O_ACCINSURED,INSIS_GEN_V10.O_PROPERTY,INSIS_GEN_V10.O_SHIP,INSIS_GEN_V10.POLICY,INSIS_GEN_V10.POLICY_AGENTS,INSIS_GEN_V10.POLICY_ALTERATIONS,INSIS_GEN_V10.POLICY_ANNEX,INSIS_GEN_V10.POLICY_CONDITIONS,INSIS_GEN_V10.POLICY_ENDORSEMENTS,INSIS_GEN_V10.POLICY_ENGAGEMENT_BILLING,INSIS_GEN_V10.POLICY_PARTICIPANTS,INSIS_GEN_V10.POLICY_RENEWAL,INSIS_GEN_V10.PREM_INST_DISC,INSIS_GEN_V10.PREM_INST_INTERIM,INSIS_GEN_V10.PREM_INST_WP,INSIS_PEOPLE_V10.P_AGENTS,INSIS_PEOPLE_V10.P_CLIENTS,INSIS_PEOPLE_V10.P_OFFICES,INSIS_PEOPLE_V10.P_PEOPLE,INSIS_PEOPLE_V10.P_STAFF,INSIS_PEOPLE_V10.P_USER_ACCOUNTS,INSIS_SYS_V10.CFG_NOM_LANGUAGE_TABLE,INSIS_SYS_V10.DOC_DOCUMENTS,INSIS_SYS_V10.QUEST_QUESTIONS,INSIS_GEN_V10.CLAIM_DOCLAD,INSIS_GEN_BLC_V10.BLC_TRANSACTIONS,INSIS_GEN_BLC_V10.BLC_APPLICATIONS,INSIS_GEN_V10.BLC_CLAIM_FRACT,INSIS_GEN_BLC_V10.BLC_PAYMENTS,INSIS_GEN_BLC_V10.BLC_PAY_INSTRUMENTS,INSIS_GEN_V10.HST_PAYMENT_MODE,INSIS_GEN_V10.HST_PAYMENT_WAY,INSIS_CUST.CUST_CLAIM_PAYMENT_REQUEST,INSIS_CUST.CUST_CLAIM_PAYMENT_REQUEST_DET,INSIS_CPX_V10.HT_CLAIM_DIAGNOSIS_TYPE,INSIS_NTW_V10.CFG_COVER_DIAGNOSIS,INSIS_NTW_V10.HT_DIAGNOSIS_GROUP_CATEGORY,INSIS_NTW_V10.HT_DIAGNOSIS,INSIS_NTW_V10.HT_DIAGNOSIS_GROUPS,INSIS_NTW_V10.CFG_DIAGNOSIS_GROUPS,INSIS_NTW_V10.HT_DIAGNOSIS_TYPE,INSIS_SYS_V10.PSDA_STEPS,INSIS_SYS_V10.PSDA_STEP_VALUES,INSIS_GEN_V10.CLAIM_INSPECTIONS remap_schema=INSIS_CUST:INSISHIST,INSIS_GEN_BLC_V10:INSISHIST,INSIS_GEN_CFG_V10:INSISHIST,INSIS_GEN_V10:INSISHIST,INSIS_PEOPLE_V10:INSISHIST,INSIS_SYS_V10:INSISHIST,INSIS_NTW_V10:INSISHIST,INSIS_CPX_V10:INSISHIST REMAP_TABLE=INSIS_CUST.CUST_CLM_HANDLERS:IC_CUSTCLMHANDLERS,INSIS_CUST.P_PROPERTY:IC_PPROPERTY,INSIS_GEN_BLC_V10.BLC_DOCUMENTS:IGBV_BLCDOCUMENTS,INSIS_GEN_BLC_V10.BLC_INSTALLMENTS:IGBV_BLCINSTALLMENTS,INSIS_GEN_CFG_V10.CFG_NL_COVER_RULES:IGCV_CFGNLCOVERRULES,INSIS_GEN_CFG_V10.CFG_NL_COVER_TEXT:IGCV_CFGNLCOVERTEXT,INSIS_GEN_CFG_V10.CFG_NL_COVERS:IGCV_CFGNLCOVERS,INSIS_GEN_CFG_V10.CFG_NL_OBJECT_RULES:IGCV_CFGNLOBJECTRULES,INSIS_GEN_CFG_V10.CFG_NL_OBJECTS:IGCV_CFGNLOBJECTS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT:IGCV_CFGNLPRODUCT,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_LAYERS:IGCV_CFGNLPRODUCTLAYERS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_PARAMS:IGCV_CFGNLPRODUCTPARAMS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_REPATTR:IGCV_CFGNLPRODUCTREPATTR,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_RULES:IGCV_CFGNLPRODUCTRULES,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_TEXT:IGCV_CFGNLPRODUCTTEXT,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_VERSIONS:IGCV_CFGNLPRODUCTVERSIONS,INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_VERSIONS_LAYERS:IGCV_CFGNLPRODUCTVERSIONSLAYER,INSIS_GEN_CFG_V10.CPR_COVER:IGCV_CPRCOVER,INSIS_GEN_CFG_V10.CPR_DISCOUNTS:IGCV_CPRDISCOUNTS,INSIS_GEN_CFG_V10.CPR_ENDORSEMENT:IGCV_CPRENDORSEMENT,INSIS_GEN_CFG_V10.CPR_LAYER:IGCV_CPRLAYER,INSIS_GEN_CFG_V10.CPR_OBJECTS:IGCV_CPROBJECTS,INSIS_GEN_CFG_V10.CPR_PARAMS:IGCV_CPRPARAMS,INSIS_GEN_CFG_V10.CPR_RULES:IGCV_CPRRULES,INSIS_GEN_CFG_V10.CPRS_COVER_RISKS:IGCV_CPRSCOVERRISKS,INSIS_GEN_CFG_V10.CPRS_DISCOUNTS:IGCV_CPRSDISCOUNTS,INSIS_GEN_CFG_V10.CPRS_ENDORSEMENT:IGCV_CPRSENDORSEMENT,INSIS_GEN_CFG_V10.CPRS_PARAM_VALUE:IGCV_CPRSPARAMVALUE,INSIS_GEN_CFG_V10.CPRS_RULE_DEFINITION:IGCV_CPRSRULEDEFINITION,INSIS_GEN_CFG_V10.SYSCFG_CLAIM_EVENTS:IGCV_SYSCFGCLAIMEVENTS,INSIS_GEN_CFG_V10.SYSCFG_PRODUCT_STATUS:IGCV_SYSCFGPRODUCTSTATUS,INSIS_GEN_CFG_V10.SYSCFG_TRANSLATIONS:IGCV_SYSCFGTRANSLATIONS,INSIS_GEN_V10.BLC_CLAIM:IGV_BLCCLAIM,INSIS_GEN_V10.BLC_POLICY_PAYMENT_PLAN:IGV_BLCPOLICYPAYMENTPLAN,INSIS_GEN_V10.CLAIM:IGV_CLAIM,INSIS_GEN_V10.CLAIM_CATASTROPHIC_EVENT:IGV_CLAIMCATASTROPHICEVENT,INSIS_GEN_V10.CLAIM_DOCLAD_BENEF_LIST:IGV_CLAIMDOCLADBENEFLIST,INSIS_GEN_V10.CLAIM_EXPENSES:IGV_CLAIMEXPENSES,INSIS_GEN_V10.CLAIM_OBJECTS:IGV_CLAIMOBJECTS,INSIS_GEN_V10.CLAIM_OBJECTS_DSCR_FRACT:IGV_CLAIMOBJECTSDSCRFRACT,INSIS_GEN_V10.CLAIM_PARTICIPANTS:IGV_CLAIMPARTICIPANTS,INSIS_GEN_V10.CLAIM_PAYMENTS:IGV_CLAIMPAYMENTS,INSIS_GEN_V10.CLAIM_PAYMENTS_DETAILS:IGV_CLAIMPAYMENTSDETAILS,INSIS_GEN_V10.CLAIM_REFUSES:IGV_CLAIMREFUSES,INSIS_GEN_V10.CLAIM_REGRESSES:IGV_CLAIMREGRESSES,INSIS_GEN_V10.CLAIM_REGRESSES_SUM:IGV_CLAIMREGRESSESSUM,INSIS_GEN_V10.CLAIM_REQUEST:IGV_CLAIMREQUEST,INSIS_GEN_V10.CLAIM_RESERVE_HISTORY:IGV_CLAIMRESERVEHISTORY,INSIS_GEN_V10.GEN_ANNEX:IGV_GENANNEX,INSIS_GEN_V10.GEN_ANNEX_REASON:IGV_GENANNEXREASON,INSIS_GEN_V10.GEN_PREMIUM_TAXES:IGV_GENPREMIUMTAXES,INSIS_GEN_V10.GEN_RESERVE_CLAIM:IGV_GENRESERVECLAIM,INSIS_GEN_V10.GEN_RESERVE_CORP:IGV_GENRESERVECORP,INSIS_GEN_V10.GEN_RISK_COVERED:IGV_GENRISKCOVERED,INSIS_GEN_V10.GEN_RISK_DISCOUNT:IGV_GENRISKDISCOUNT,INSIS_GEN_V10.GEN_RISK_INDEMNITY:IGV_GENRISKINDEMNITY,INSIS_GEN_V10.GEN_RISK_RISKS:IGV_GENRISKRISKS,INSIS_GEN_V10.HST_CLAIM_STATE:IGV_HSTCLAIMSTATE,INSIS_GEN_V10.HST_ENG_POLICY_TYPE:IGV_HSTENGPOLICYTYPE,INSIS_GEN_V10.HST_OBJECT_TYPE:IGV_HSTOBJECTTYPE,INSIS_GEN_V10.HT_ANNEX_REASON:IGV_HTANNEXREASON,INSIS_GEN_V10.HT_CLAIM_CATASTROPHIC_EVENTS:IGV_HTCLAIMCATASTROPHICEVENTS,INSIS_GEN_V10.HT_CLAIM_REFUSE:IGV_HTCLAIMREFUSE,INSIS_GEN_V10.INSURED_OBJECT:IGV_INSUREDOBJECT,INSIS_GEN_V10.O_ACCINSURED:IGV_OACCINSURED,INSIS_GEN_V10.O_PROPERTY:IGV_OPROPERTY,INSIS_GEN_V10.O_SHIP:IGV_OSHIP,INSIS_GEN_V10.POLICY:IGV_POLICY,INSIS_GEN_V10.POLICY_AGENTS:IGV_POLICYAGENTS,INSIS_GEN_V10.POLICY_ALTERATIONS:IGV_POLICYALTERATIONS,INSIS_GEN_V10.POLICY_ANNEX:IGV_POLICYANNEX,INSIS_GEN_V10.POLICY_CONDITIONS:IGV_POLICYCONDITIONS,INSIS_GEN_V10.POLICY_ENDORSEMENTS:IGV_POLICYENDORSEMENTS,INSIS_GEN_V10.POLICY_ENGAGEMENT_BILLING:IGV_POLICYENGAGEMENTBILLING,INSIS_GEN_V10.POLICY_PARTICIPANTS:IGV_POLICYPARTICIPANTS,INSIS_GEN_V10.POLICY_RENEWAL:IGV_POLICYRENEWAL,INSIS_GEN_V10.PREM_INST_DISC:IGV_PREMINSTDISC,INSIS_GEN_V10.PREM_INST_INTERIM:IGV_PREMINSTINTERIM,INSIS_GEN_V10.PREM_INST_WP:IGV_PREMINSTWP,INSIS_PEOPLE_V10.P_AGENTS:IPV_PAGENTS,INSIS_PEOPLE_V10.P_CLIENTS:IPV_PCLIENTS,INSIS_PEOPLE_V10.P_OFFICES:IPV_POFFICES,INSIS_PEOPLE_V10.P_PEOPLE:IPV_PPEOPLE,INSIS_PEOPLE_V10.P_STAFF:IPV_PSTAFF,INSIS_PEOPLE_V10.P_USER_ACCOUNTS:IPV_PUSERACCOUNTS,INSIS_SYS_V10.CFG_NOM_LANGUAGE_TABLE:ISV_CFGNOMLANGUAGETABLE,INSIS_SYS_V10.DOC_DOCUMENTS:ISV_DOCDOCUMENTS,INSIS_SYS_V10.QUEST_QUESTIONS:ISV_QUESTQUESTIONS,INSIS_CUST.P_PROPERTY_ADDRESS:IC_PPROPERTYADDRESS,INSIS_CUST.P_PROPERTY_BUILDING:IC_PPROPERTYBUILDING, INSIS_CUST.RISK_CODES_MAPPING:IC_RISKCODESMAPPING,INSIS_CUST.POLICY_LABEL:IC_POLICYLABEL,INSIS_GEN_V10.CLAIM_DOCLAD:IGV_CLAIMDOCLAD, INSIS_GEN_BLC_V10.BLC_TRANSACTIONS:IGBV_BLCTRANSACTIONS,INSIS_GEN_BLC_V10.BLC_APPLICATIONS:IGBV_BLCAPPLICATIONS,INSIS_GEN_V10.BLC_CLAIM_FRACT:IGV_BLCCLAIMFRACT,INSIS_GEN_BLC_V10.BLC_PAYMENTS:IGBV_BLCPAYMENTS,INSIS_GEN_BLC_V10.BLC_PAY_INSTRUMENTS:IGBV_BLCPAYINSTRUMENTS,INSIS_GEN_V10.HST_PAYMENT_MODE:IGV_HSTPAYMENTMODE,INSIS_GEN_V10.HST_PAYMENT_WAY:IGV_HSTPAYMENTWAY,INSIS_CUST.CUST_CLAIM_PAYMENT_REQUEST:IC_CUSTCLAIMPAYMENT_REQUEST,INSIS_CUST.CUST_CLAIM_PAYMENT_REQUEST_DET:IC_CUSTCLM_PAYMENT_REQ_DET,INSIS_CPX_V10.HT_CLAIM_DIAGNOSIS_TYPE:ICV_HTCLAIM_DIAGNOSISTYPE,INSIS_NTW_V10.CFG_COVER_DIAGNOSIS:INV_CFGCOVERDIAGNOSIS,INSIS_NTW_V10.HT_DIAGNOSIS_GROUP_CATEGORY:INV_HTDIAGNOSIS_GROUPCATEGORY,INSIS_NTW_V10.HT_DIAGNOSIS:INV_HTDIAGNOSIS,INSIS_NTW_V10.HT_DIAGNOSIS_GROUPS:INV_HTDIAGNOSISGROUPS,INSIS_NTW_V10.CFG_DIAGNOSIS_GROUPS:INV_CFGDIAGNOSISGROUPS,INSIS_NTW_V10.HT_DIAGNOSIS_TYPE:INV_HTDIAGNOSISTYPE,INSIS_SYS_V10.PSDA_STEPS:ISV_PSDASTEPS,INSIS_SYS_V10.PSDA_STEP_VALUES:ISV_PSDASTEPVALUES,INSIS_GEN_V10.CLAIM_INSPECTIONS:IGV_CLAIM_INSPECTIONS dumpfile=GG_Tables.dmp logfile=GG_Tables_imp.log CONTENT=DATA_ONLY TABLE_EXISTS_ACTION=TRUNCATE


Change SRC_COMMIT_TS back to null:
==================================

ALTER TABLE INSISHIST.IC_CUSTCLMHANDLERS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IC_PPROPERTY MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGBV_BLCDOCUMENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGBV_BLCINSTALLMENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLCOVERRULES MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLCOVERTEXT MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLCOVERS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLOBJECTRULES MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLOBJECTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCT MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTLAYERS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTPARAMS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTREPATTR MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTRULES MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTTEXT MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTVERSIONS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CFGNLPRODUCTVERSIONSLAYER MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRCOVER MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRDISCOUNTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRENDORSEMENT MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRLAYER MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPROBJECTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRPARAMS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRRULES MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRSCOVERRISKS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRSDISCOUNTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRSENDORSEMENT MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRSPARAMVALUE MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_CPRSRULEDEFINITION MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_SYSCFGCLAIMEVENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_SYSCFGPRODUCTSTATUS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGCV_SYSCFGTRANSLATIONS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_BLCCLAIM MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_BLCPOLICYPAYMENTPLAN MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIM MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMCATASTROPHICEVENT MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMDOCLADBENEFLIST MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMEXPENSES MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMOBJECTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMOBJECTSDSCRFRACT MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMPARTICIPANTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMPAYMENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMPAYMENTSDETAILS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMREFUSES MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMREGRESSES MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMREGRESSESSUM MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMREQUEST MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMRESERVEHISTORY MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_GENANNEX MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_GENANNEXREASON MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_GENPREMIUMTAXES MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_GENRESERVECLAIM MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_GENRESERVECORP MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_GENRISKCOVERED MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_GENRISKDISCOUNT MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_GENRISKINDEMNITY MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_GENRISKRISKS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_HSTCLAIMSTATE MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_HSTENGPOLICYTYPE MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_HSTOBJECTTYPE MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_HTANNEXREASON MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_HTCLAIMCATASTROPHICEVENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_HTCLAIMREFUSE MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_INSUREDOBJECT MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_OACCINSURED MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_OPROPERTY MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_OSHIP MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_POLICY MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_POLICYAGENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_POLICYALTERATIONS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_POLICYANNEX MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_POLICYCONDITIONS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_POLICYENDORSEMENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_POLICYENGAGEMENTBILLING MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_POLICYPARTICIPANTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_POLICYRENEWAL MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_PREMINSTDISC MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_PREMINSTINTERIM MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_PREMINSTWP MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IPV_PAGENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IPV_PCLIENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IPV_POFFICES MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IPV_PPEOPLE MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IPV_PSTAFF MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IPV_PUSERACCOUNTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.ISV_CFGNOMLANGUAGETABLE MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.ISV_DOCDOCUMENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.ISV_QUESTQUESTIONS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IC_PPROPERTYADDRESS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IC_PPROPERTYBUILDING MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IC_RISKCODESMAPPING MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IC_POLICYLABEL MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIMDOCLAD MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGBV_BLCTRANSACTIONS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGBV_BLCAPPLICATIONS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_BLCCLAIMFRACT MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGBV_BLCPAYMENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGBV_BLCPAYINSTRUMENTS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_HSTPAYMENTMODE MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_HSTPAYMENTWAY MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IC_CUSTCLAIMPAYMENT_REQUEST MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IC_CUSTCLM_PAYMENT_REQ_DET MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.ICV_HTCLAIM_DIAGNOSISTYPE MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.INV_CFGCOVERDIAGNOSIS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.INV_HTDIAGNOSIS_GROUPCATEGORY MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.INV_HTDIAGNOSIS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.INV_HTDIAGNOSISGROUPS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.INV_CFGDIAGNOSISGROUPS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.INV_HTDIAGNOSISTYPE MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.ISV_PSDASTEPS MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.ISV_PSDASTEPVALUES MODIFY SRC_COMMIT_TS DEFAULT null;
ALTER TABLE INSISHIST.IGV_CLAIM_INSPECTIONS MODIFY SRC_COMMIT_TS DEFAULT null;


Add trandata for all table:
============================

login to ggsci

DBLogin UserIDAlias oggpdbadmin
add trandata INSIS_CUST.CUST_CLAIM_PAYMENT_REQUEST ALLCOLS
add trandata INSIS_CUST.CUST_CLAIM_PAYMENT_REQUEST_DET ALLCOLS
add trandata INSIS_CUST.CUST_CLM_HANDLERS ALLCOLS
add trandata INSIS_CUST.POLICY_LABEL ALLCOLS
add trandata INSIS_CUST.P_PROPERTY ALLCOLS
add trandata INSIS_CUST.P_PROPERTY_ADDRESS ALLCOLS
add trandata INSIS_CUST.P_PROPERTY_BUILDING ALLCOLS
add trandata INSIS_CUST.RISK_CODES_MAPPING ALLCOLS
add trandata INSIS_CPX_V10.HT_CLAIM_DIAGNOSIS_TYPE ALLCOLS
add trandata INSIS_GEN_BLC_V10.BLC_APPLICATIONS ALLCOLS
add trandata INSIS_GEN_BLC_V10.BLC_DOCUMENTS ALLCOLS
add trandata INSIS_GEN_BLC_V10.BLC_INSTALLMENTS ALLCOLS
add trandata INSIS_GEN_BLC_V10.BLC_PAY_INSTRUMENTS ALLCOLS
add trandata INSIS_GEN_BLC_V10.BLC_PAYMENTS ALLCOLS
add trandata INSIS_GEN_BLC_V10.BLC_TRANSACTIONS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_COVER_RULES ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_COVERS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_COVER_TEXT ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_OBJECT_RULES ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_OBJECTS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_PRODUCT ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_LAYERS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_PARAMS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_REPATTR ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_RULES ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_TEXT ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_VERSIONS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_VERSIONS_LAYERS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPR_COVER ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPR_DISCOUNTS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPR_ENDORSEMENT ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPR_LAYER ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPR_OBJECTS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPR_PARAMS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPR_RULES ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPRS_COVER_RISKS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPRS_DISCOUNTS ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPRS_ENDORSEMENT ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPRS_PARAM_VALUE ALLCOLS
add trandata INSIS_GEN_CFG_V10.CPRS_RULE_DEFINITION ALLCOLS
add trandata INSIS_GEN_CFG_V10.SYSCFG_CLAIM_EVENTS ALLCOLS
add trandata INSIS_GEN_CFG_V10.SYSCFG_PRODUCT_STATUS ALLCOLS
add trandata INSIS_GEN_CFG_V10.SYSCFG_TRANSLATIONS ALLCOLS
add trandata INSIS_GEN_V10.BLC_CLAIM ALLCOLS
add trandata INSIS_GEN_V10.BLC_CLAIM_FRACT ALLCOLS
add trandata INSIS_GEN_V10.BLC_POLICY_PAYMENT_PLAN ALLCOLS
add trandata INSIS_GEN_V10.CLAIM ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_INSPECTIONS ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_CATASTROPHIC_EVENT ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_DOCLAD ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_DOCLAD_BENEF_LIST ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_EXPENSES ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_OBJECTS ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_OBJECTS_DSCR_FRACT ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_PARTICIPANTS ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_PAYMENTS ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_PAYMENTS_DETAILS ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_REFUSES ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_REGRESSES ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_REGRESSES_SUM ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_REQUEST ALLCOLS
add trandata INSIS_GEN_V10.CLAIM_RESERVE_HISTORY ALLCOLS
add trandata INSIS_GEN_V10.GEN_ANNEX ALLCOLS
add trandata INSIS_GEN_V10.GEN_ANNEX_REASON ALLCOLS
add trandata INSIS_GEN_V10.GEN_PREMIUM_TAXES ALLCOLS
add trandata INSIS_GEN_V10.GEN_RESERVE_CLAIM ALLCOLS
add trandata INSIS_GEN_V10.GEN_RESERVE_CORP ALLCOLS
add trandata INSIS_GEN_V10.GEN_RISK_COVERED ALLCOLS
add trandata INSIS_GEN_V10.GEN_RISK_DISCOUNT ALLCOLS
add trandata INSIS_GEN_V10.GEN_RISK_INDEMNITY ALLCOLS
add trandata INSIS_GEN_V10.GEN_RISK_RISKS ALLCOLS
add trandata INSIS_GEN_V10.HST_CLAIM_STATE ALLCOLS
add trandata INSIS_GEN_V10.HST_ENG_POLICY_TYPE ALLCOLS
add trandata INSIS_GEN_V10.HST_OBJECT_TYPE ALLCOLS
add trandata INSIS_GEN_V10.HST_PAYMENT_MODE ALLCOLS
add trandata INSIS_GEN_V10.HST_PAYMENT_WAY ALLCOLS
add trandata INSIS_GEN_V10.HT_ANNEX_REASON ALLCOLS
add trandata INSIS_GEN_V10.HT_CLAIM_CATASTROPHIC_EVENTS ALLCOLS
add trandata INSIS_GEN_V10.HT_CLAIM_REFUSE ALLCOLS
add trandata INSIS_GEN_V10.INSURED_OBJECT ALLCOLS
add trandata INSIS_GEN_V10.O_ACCINSURED ALLCOLS
add trandata INSIS_GEN_V10.O_PROPERTY ALLCOLS
add trandata INSIS_GEN_V10.O_SHIP ALLCOLS
add trandata INSIS_GEN_V10.POLICY ALLCOLS
add trandata INSIS_GEN_V10.POLICY_AGENTS ALLCOLS
add trandata INSIS_GEN_V10.POLICY_ALTERATIONS ALLCOLS
add trandata INSIS_GEN_V10.POLICY_ANNEX ALLCOLS
add trandata INSIS_GEN_V10.POLICY_CONDITIONS ALLCOLS
add trandata INSIS_GEN_V10.POLICY_ENDORSEMENTS ALLCOLS
add trandata INSIS_GEN_V10.POLICY_ENGAGEMENT_BILLING ALLCOLS
add trandata INSIS_GEN_V10.POLICY_PARTICIPANTS ALLCOLS
add trandata INSIS_GEN_V10.POLICY_RENEWAL ALLCOLS
add trandata INSIS_GEN_V10.PREM_INST_DISC ALLCOLS
add trandata INSIS_GEN_V10.PREM_INST_INTERIM ALLCOLS
add trandata INSIS_GEN_V10.PREM_INST_WP ALLCOLS
add trandata INSIS_NTW_V10.CFG_COVER_DIAGNOSIS ALLCOLS
add trandata INSIS_NTW_V10.CFG_DIAGNOSIS_GROUPS ALLCOLS
add trandata INSIS_NTW_V10.HT_DIAGNOSIS ALLCOLS
add trandata INSIS_NTW_V10.HT_DIAGNOSIS_GROUP_CATEGORY ALLCOLS
add trandata INSIS_NTW_V10.HT_DIAGNOSIS_GROUPS ALLCOLS
add trandata INSIS_NTW_V10.HT_DIAGNOSIS_TYPE ALLCOLS
add trandata INSIS_PEOPLE_V10.P_AGENTS ALLCOLS
add trandata INSIS_PEOPLE_V10.P_CLIENTS ALLCOLS
add trandata INSIS_PEOPLE_V10.P_OFFICES ALLCOLS
add trandata INSIS_PEOPLE_V10.P_PEOPLE ALLCOLS
add trandata INSIS_PEOPLE_V10.P_STAFF ALLCOLS
add trandata INSIS_PEOPLE_V10.P_USER_ACCOUNTS ALLCOLS
add trandata INSIS_SYS_V10.CFG_NOM_LANGUAGE_TABLE ALLCOLS
add trandata INSIS_SYS_V10.DOC_DOCUMENTS ALLCOLS
add trandata INSIS_SYS_V10.PSDA_STEPS ALLCOLS
add trandata INSIS_SYS_V10.PSDA_STEP_VALUES ALLCOLS
add trandata INSIS_SYS_V10.QUEST_QUESTIONS ALLCOLS


Start replicat:
===============

start replicat if you want to continue with older scn which we noted at time of starting extract.This helps in no data loss


or start replicat from current time:
====================================
START REPLICAT INRDW AFTERCSN %CURRENTSCN%



















