#!/bin/bash

#Variable Declaration
FILE_DIR=/tmp
export FILE_DIR;
ORACLE_HOME=/u01/app/oracle/rdbms19c
export ORACLE_HOME;
ORACLE_SID=INSISDR1
export ORACLE_SID;
export PATH=$ORACLE_HOME/bin:$PATH

SOURCE_TAB=(
INSIS_CUST.CUST_CLM_HANDLERS
INSIS_CUST.POLICY_LABEL
INSIS_CUST.P_PROPERTY
INSIS_CUST.P_PROPERTY_ADDRESS
INSIS_CUST.P_PROPERTY_BUILDING
INSIS_CUST.RISK_CODES_MAPPING
INSIS_GEN_BLC_V10.BLC_DOCUMENTS
INSIS_GEN_CFG_V10.CFG_NL_COVER_RULES
INSIS_GEN_CFG_V10.CFG_NL_COVERS
INSIS_GEN_CFG_V10.CFG_NL_COVER_TEXT
INSIS_GEN_CFG_V10.CFG_NL_OBJECT_RULES
INSIS_GEN_CFG_V10.CFG_NL_OBJECTS
INSIS_GEN_CFG_V10.CFG_NL_PRODUCT
INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_LAYERS
INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_PARAMS
INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_REPATTR
INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_RULES
INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_TEXT
INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_VERSIONS
INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_VERSIONS_LAYERS
INSIS_GEN_CFG_V10.CPR_COVER
INSIS_GEN_CFG_V10.CPR_DISCOUNTS
INSIS_GEN_CFG_V10.CPR_ENDORSEMENT
INSIS_GEN_CFG_V10.CPR_LAYER
INSIS_GEN_CFG_V10.CPR_OBJECTS
INSIS_GEN_CFG_V10.CPR_PARAMS
INSIS_GEN_CFG_V10.CPR_RULES
INSIS_GEN_CFG_V10.CPRS_COVER_RISKS
INSIS_GEN_CFG_V10.CPRS_DISCOUNTS
INSIS_GEN_CFG_V10.CPRS_ENDORSEMENT
INSIS_GEN_CFG_V10.CPRS_PARAM_VALUE
INSIS_GEN_CFG_V10.CPRS_RULE_DEFINITION
INSIS_GEN_CFG_V10.SYSCFG_CLAIM_EVENTS
INSIS_GEN_CFG_V10.SYSCFG_PRODUCT_STATUS
INSIS_GEN_CFG_V10.SYSCFG_TRANSLATIONS
INSIS_GEN_V10.BLC_CLAIM
INSIS_GEN_V10.BLC_POLICY_PAYMENT_PLAN
INSIS_GEN_V10.CLAIM
INSIS_GEN_V10.CLAIM_CATASTROPHIC_EVENT
INSIS_GEN_V10.CLAIM_DOCLAD_BENEF_LIST
INSIS_GEN_V10.CLAIM_EXPENSES
INSIS_GEN_V10.CLAIM_OBJECTS
INSIS_GEN_V10.CLAIM_OBJECTS_DSCR_FRACT
INSIS_GEN_V10.CLAIM_PARTICIPANTS
INSIS_GEN_V10.CLAIM_PAYMENTS
INSIS_GEN_V10.CLAIM_PAYMENTS_DETAILS
INSIS_GEN_V10.CLAIM_REFUSES
INSIS_GEN_V10.CLAIM_REGRESSES
INSIS_GEN_V10.CLAIM_REGRESSES_SUM
INSIS_GEN_V10.CLAIM_REQUEST
INSIS_GEN_V10.CLAIM_RESERVE_HISTORY
INSIS_GEN_V10.GEN_ANNEX
INSIS_GEN_V10.GEN_ANNEX_REASON
INSIS_GEN_V10.GEN_PREMIUM_TAXES
INSIS_GEN_V10.GEN_RESERVE_CLAIM
INSIS_GEN_V10.GEN_RESERVE_CORP
INSIS_GEN_V10.GEN_RISK_INDEMNITY
INSIS_GEN_V10.GEN_RISK_RISKS
INSIS_GEN_V10.HST_CLAIM_STATE
INSIS_GEN_V10.HST_ENG_POLICY_TYPE
INSIS_GEN_V10.HST_OBJECT_TYPE
INSIS_GEN_V10.HT_ANNEX_REASON
INSIS_GEN_V10.HT_CLAIM_CATASTROPHIC_EVENTS
INSIS_GEN_V10.HT_CLAIM_REFUSE
INSIS_GEN_V10.O_ACCINSURED
INSIS_GEN_V10.O_PROPERTY
INSIS_GEN_V10.O_SHIP
INSIS_GEN_V10.POLICY_AGENTS
INSIS_GEN_V10.POLICY_ALTERATIONS
INSIS_GEN_V10.POLICY_ANNEX
INSIS_GEN_V10.POLICY_CONDITIONS
INSIS_GEN_V10.POLICY_ENDORSEMENTS
INSIS_GEN_V10.POLICY_ENGAGEMENT_BILLING
INSIS_GEN_V10.POLICY_PARTICIPANTS
INSIS_GEN_V10.PREM_INST_DISC
INSIS_PEOPLE_V10.P_AGENTS
INSIS_PEOPLE_V10.P_CLIENTS
INSIS_PEOPLE_V10.P_OFFICES
INSIS_PEOPLE_V10.P_PEOPLE
INSIS_PEOPLE_V10.P_STAFF
INSIS_PEOPLE_V10.P_USER_ACCOUNTS
INSIS_SYS_V10.CFG_NOM_LANGUAGE_TABLE
INSIS_SYS_V10.DOC_DOCUMENTS
INSIS_GEN_V10.CLAIM_DOCLAD
INSIS_GEN_BLC_V10.BLC_APPLICATIONS
INSIS_GEN_V10.BLC_CLAIM_FRACT
INSIS_GEN_BLC_V10.BLC_PAY_INSTRUMENTS
INSIS_GEN_V10.HST_PAYMENT_MODE
INSIS_GEN_V10.HST_PAYMENT_WAY
INSIS_CUST.CUST_CLAIM_PAYMENT_REQUEST
INSIS_CUST.CUST_CLAIM_PAYMENT_REQUEST_DET
INSIS_CPX_V10.HT_CLAIM_DIAGNOSIS_TYPE
INSIS_NTW_V10.CFG_COVER_DIAGNOSIS
INSIS_NTW_V10.HT_DIAGNOSIS_GROUP_CATEGORY
INSIS_NTW_V10.HT_DIAGNOSIS
INSIS_NTW_V10.HT_DIAGNOSIS_GROUPS
INSIS_NTW_V10.CFG_DIAGNOSIS_GROUPS
INSIS_NTW_V10.HT_DIAGNOSIS_TYPE
INSIS_SYS_V10.PSDA_STEPS
INSIS_SYS_V10.PSDA_STEP_VALUES
INSIS_GEN_V10.CLAIM_INSPECTIONS
)

TARGET_TAB=(
INSISHIST.IC_CUSTCLMHANDLERS
INSISHIST.IC_POLICYLABEL
INSISHIST.IC_PPROPERTY
INSISHIST.IC_PPROPERTYADDRESS
INSISHIST.IC_PPROPERTYBUILDING
INSISHIST.IC_RISKCODESMAPPING
INSISHIST.IGBV_BLCDOCUMENTS
INSISHIST.IGCV_CFGNLCOVERRULES
INSISHIST.IGCV_CFGNLCOVERS
INSISHIST.IGCV_CFGNLCOVERTEXT
INSISHIST.IGCV_CFGNLOBJECTRULES
INSISHIST.IGCV_CFGNLOBJECTS
INSISHIST.IGCV_CFGNLPRODUCT
INSISHIST.IGCV_CFGNLPRODUCTLAYERS
INSISHIST.IGCV_CFGNLPRODUCTPARAMS
INSISHIST.IGCV_CFGNLPRODUCTREPATTR
INSISHIST.IGCV_CFGNLPRODUCTRULES
INSISHIST.IGCV_CFGNLPRODUCTTEXT
INSISHIST.IGCV_CFGNLPRODUCTVERSIONS
INSISHIST.IGCV_CFGNLPRODUCTVERSIONSLAYER
INSISHIST.IGCV_CPRCOVER
INSISHIST.IGCV_CPRDISCOUNTS
INSISHIST.IGCV_CPRENDORSEMENT
INSISHIST.IGCV_CPRLAYER
INSISHIST.IGCV_CPROBJECTS
INSISHIST.IGCV_CPRPARAMS
INSISHIST.IGCV_CPRRULES
INSISHIST.IGCV_CPRSCOVERRISKS
INSISHIST.IGCV_CPRSDISCOUNTS
INSISHIST.IGCV_CPRSENDORSEMENT
INSISHIST.IGCV_CPRSPARAMVALUE
INSISHIST.IGCV_CPRSRULEDEFINITION
INSISHIST.IGCV_SYSCFGCLAIMEVENTS
INSISHIST.IGCV_SYSCFGPRODUCTSTATUS
INSISHIST.IGCV_SYSCFGTRANSLATIONS
INSISHIST.IGV_BLCCLAIM
INSISHIST.IGV_BLCPOLICYPAYMENTPLAN
INSISHIST.IGV_CLAIM
INSISHIST.IGV_CLAIMCATASTROPHICEVENT
INSISHIST.IGV_CLAIMDOCLADBENEFLIST
INSISHIST.IGV_CLAIMEXPENSES
INSISHIST.IGV_CLAIMOBJECTS
INSISHIST.IGV_CLAIMOBJECTSDSCRFRACT
INSISHIST.IGV_CLAIMPARTICIPANTS
INSISHIST.IGV_CLAIMPAYMENTS
INSISHIST.IGV_CLAIMPAYMENTSDETAILS
INSISHIST.IGV_CLAIMREFUSES
INSISHIST.IGV_CLAIMREGRESSES
INSISHIST.IGV_CLAIMREGRESSESSUM
INSISHIST.IGV_CLAIMREQUEST
INSISHIST.IGV_CLAIMRESERVEHISTORY
INSISHIST.IGV_GENANNEX
INSISHIST.IGV_GENANNEXREASON
INSISHIST.IGV_GENPREMIUMTAXES
INSISHIST.IGV_GENRESERVECLAIM
INSISHIST.IGV_GENRESERVECORP
INSISHIST.IGV_GENRISKINDEMNITY
INSISHIST.IGV_GENRISKRISKS
INSISHIST.IGV_HSTCLAIMSTATE
INSISHIST.IGV_HSTENGPOLICYTYPE
INSISHIST.IGV_HSTOBJECTTYPE
INSISHIST.IGV_HTANNEXREASON
INSISHIST.IGV_HTCLAIMCATASTROPHICEVENTS
INSISHIST.IGV_HTCLAIMREFUSE
INSISHIST.IGV_OACCINSURED
INSISHIST.IGV_OPROPERTY
INSISHIST.IGV_OSHIP
INSISHIST.IGV_POLICYAGENTS
INSISHIST.IGV_POLICYALTERATIONS
INSISHIST.IGV_POLICYANNEX
INSISHIST.IGV_POLICYCONDITIONS
INSISHIST.IGV_POLICYENDORSEMENTS
INSISHIST.IGV_POLICYENGAGEMENTBILLING
INSISHIST.IGV_POLICYPARTICIPANTS
INSISHIST.IGV_PREMINSTDISC
INSISHIST.IPV_PAGENTS
INSISHIST.IPV_PCLIENTS
INSISHIST.IPV_POFFICES
INSISHIST.IPV_PPEOPLE
INSISHIST.IPV_PSTAFF
INSISHIST.IPV_PUSERACCOUNTS
INSISHIST.ISV_CFGNOMLANGUAGETABLE
INSISHIST.ISV_DOCDOCUMENTS
INSISHIST.IGV_CLAIMDOCLAD
INSISHIST.IGBV_BLCAPPLICATIONS
INSISHIST.IGV_BLCCLAIMFRACT
INSISHIST.IGBV_BLCPAYINSTRUMENTS
INSISHIST.IGV_HSTPAYMENTMODE
INSISHIST.IGV_HSTPAYMENTWAY
INSISHIST.IC_CUSTCLAIMPAYMENT_REQUEST
INSISHIST.IC_CUSTCLM_PAYMENT_REQ_DET
INSISHIST.ICV_HTCLAIM_DIAGNOSISTYPE
INSISHIST.INV_CFGCOVERDIAGNOSIS
INSISHIST.INV_HTDIAGNOSIS_GROUPCATEGORY
INSISHIST.INV_HTDIAGNOSIS
INSISHIST.INV_HTDIAGNOSISGROUPS
INSISHIST.INV_CFGDIAGNOSISGROUPS
INSISHIST.INV_HTDIAGNOSISTYPE
INSISHIST.ISV_PSDASTEPS
INSISHIST.ISV_PSDASTEPVALUES
INSISHIST.IGV_CLAIM_INSPECTIONS
)

CONDITION_ARR=(
ID
ID
PROPERTY_ID
PROPERTY_ADDRESS_ID
PROPERTY_BUILDING_ID
PRODUCT_CODE
DOC_ID
COVER_RULE_ID
COVER_LINK_ID
COVER_TEXT_ID
OBJ_RULES_ID
OBJECT_LINK_ID
PRODUCT_LINK_ID
CFG_ID,LAYER_ID
PRODUCT_NAME_ID
PRODUCT_REPOS_ID
PRODUCT_RULE_ID
PRODUCT_TEXT_ID
PRODUCT_LINK_ID,VERSION
CFG_ID,VERSION,LAYER_ID
COVER_CPR_ID
DISC_CPR_ID
ENDORSMENT_CPR_ID
LAYER_CPR_ID
OBJECT_TYPE_CPR_ID
PARAM_CPR_ID
RULE_CPR_ID
CPRS_RISK_ID
DISC_CPR_ID
ENDORSMENT_CPR_ID
PARAM_VALUE_CPR_ID
RULE_CPR_ID,RULE_ORDER
ID
ID
TABLE_NAME,ID,COLUMN_NAME,LANGUAGE
BLC_CLM_PK
POLICY_PPLAN_ID
CLAIM_ID
CAT_EVENT_ID
LIST_ID
CLAIM_EXP_SEQ
CLAIM_OBJ_SEQ
FRACT_SEQ
PARTICIPANT_ID
PAYMENT_ID
DETAIL_ID
REFUSE_SEQ
REGRESS_ID
REGRESS_SUM_ID
CLAIM_ID,REQUEST_ID
RESERV_SEQ
ANNEX_ID,POLICY_ID
POLICY_ID,ANNEX_ID,ANNEX_REASON
PREMTAX_ID
CLAIM_OBJ_SEQ,RESERVE_DATE,REQUEST_ID,CLAIM_ID,COVER_TYPE
POLICY_ID,PREMINST_ID,INSURED_OBJ_ID,COVER_TYPE,RESERVE_DATE,STATUS,FRACTION_TYPE
INSURED_OBJ_ID,POLICY_ID,ANNEX_ID,COVER_TYPE,FRANCHISE_CLAIM
INSURED_OBJ_ID,COVER_TYPE,POLICY_ID,ANNEX_ID,RISK_TYPE
STATE_ID
ID
ID
ID
ID
ID
OBJECT_ID
OBJECT_ID
OBJECT_ID
POLICY_AGENT_ID
POLICY_ID,ANNEX_ID
POLICY_ID,ANNEX_ID,INSR_TYPE
POLICY_ID,ANNEX_ID,INSR_TYPE,COVER_TYPE,COND_TYPE
ENDORSEMENT_ID
ENG_BILLING_ID
PARTICIPANT_ID
PREM_DISC_ID
AGENT_ID
CLIENT_ID
OFFICE_ID
MAN_ID
STAFF_ID
ACCOUNT_ID
TABLE_NAME,ID,LANGUAGE
DOC_SEQ
DOCLAD_ID
APPLICATION_ID
BLC_CLM_PK,LOB,GL_FRACT,COVER_TYPE
INSTRUMENT_ID,VERSION
ID
PAYMENT_WAY
PAYM_REQUEST_ID
PAYM_REQUEST_ID,CLAIM_OBJ_SEQ
ID
INSR_TYPE,COVER_TYPE,DIAGNOSIS_GROUP_ID,DIAGNOSIS_ID,COUNTRY_ID,VALID_FROM
ID
DIAGNOSIS_ID
GROUP_ID
DETAIL_ID
ID
PSDA_STEP_ID
PSDA_STEP_ID,PARAM_ID
CLAIM_OBJ_SEQ,CLAIM_ID,REQUEST_ID,INSPECT_NUM
)


# Check, if log file exist then delete
FILE=${FILE_DIR}/GG_TAB_Replication.log
FILE2=${FILE_DIR}/Info_TAB_Replication.log
if [ -f "$FILE" ];
        then
        rm ${FILE_DIR}/GG_TAB_Replication.log
fi

# Starting new logfile
echo "=========================== Log for GoldenGate table level data validation  ==================================" > ${FILE_DIR}/GG_TAB_Replication.log
echo "INSIS Table Name |  GG Schema Table Name  |  Difference in data count" >> ${FILE_DIR}/GG_TAB_Replication.log
echo "=====================================================================" >> ${FILE_DIR}/GG_TAB_Replication.log

if [ -f "$FILE2" ];
        then
        rm ${FILE_DIR}/GG_TAB_Replication2.log
fi

# Starting new logfile
echo "=========================== Log for GoldenGate table level data validation  ==================================" > ${FILE_DIR}/GG_TAB_Replication2.log
echo "INSIS Table Name |  GG Schema Table Name  |  Difference in data count" >> ${FILE_DIR}/GG_TAB_Replication2.log
echo "=====================================================================" >> ${FILE_DIR}/GG_TAB_Replication2.log

# Count of array length
total=${#SOURCE_TAB[*]}

# Starting Loop to compare all the INSIS table data with corresponding GoldenGate tables which is in DW replication
for (( i=0; i<=$(( $total -1 )); i++ ))
do
    #echo ${SOURCE_TAB[i]} " | " ${TARGET_TAB[i]}  " | " ${CONDITION_ARR[i]}

# 10 minutes before SCN of database
DB_SCN=$(${ORACLE_HOME}/bin/sqlplus -S "/ as sysdba" <<EOF
set pages 0 feedback off ;
select timestamp_to_scn(SYSTIMESTAMP - 10/24/60) from dual;
exit;
EOF
)

# Building the query to compare the data in manner of INSIS - GG where row modification time was less than 10 min of current time
Comp_sql="SELECT COUNT(*) FROM (SELECT "${CONDITION_ARR[i]}"  from "${SOURCE_TAB[i]}" WHERE ORA_ROWSCN <= "$DB_SCN" MINUS SELECT "${CONDITION_ARR[i]}" from "${TARGET_TAB[i]}");"

# Execute the query and get the count of data mismatch in variable Count
Count=$(${ORACLE_HOME}/bin/sqlplus -S "/ as sysdba" <<EOF
set pages 0 feedback off ;
$Comp_sql
exit;
EOF
)

# Condition statement to write in the logfile
if [ $Count -gt 0 ]
then
        # Puch the data to logfile  if there is data difference
        echo ${SOURCE_TAB[i]} " | " ${TARGET_TAB[i]}  " | " $Count >> ${FILE_DIR}/GG_TAB_Replication.log

        # Write to query to log which found the data mismatch
       # echo $Comp_sql >> ${FILE_DIR}/GG_TAB_Replication.log
fi

# Condition statement to puch the compare result to logfile in case of no difference also (Info message)
 if [ $Count -eq 0 ]; then
        # Puch the data to logfile even if there is no data difference (Not necessary) remove the comment from below line when need info email
        echo ${SOURCE_TAB[i]} " | " ${TARGET_TAB[i]}  " | " $Count >> ${FILE_DIR}/GG_TAB_Replication2.log
 fi

done
# End of loop

echo "============================Purged tables=========================================" >> ${FILE_DIR}/GG_TAB_Replication.log



SOURCE_TAB=(
INSIS_GEN_BLC_V10.BLC_INSTALLMENTS
INSIS_GEN_V10.GEN_RISK_COVERED
INSIS_GEN_V10.GEN_RISK_DISCOUNT
INSIS_GEN_V10.POLICY
INSIS_GEN_V10.INSURED_OBJECT
INSIS_GEN_V10.POLICY_RENEWAL
INSIS_GEN_V10.PREM_INST_INTERIM
INSIS_GEN_V10.PREM_INST_WP
INSIS_GEN_BLC_V10.BLC_TRANSACTIONS
INSIS_GEN_BLC_V10.BLC_PAYMENTS
INSIS_SYS_V10.QUEST_QUESTIONS
)

TARGET_TAB=(
INSISHIST.IGBV_BLCINSTALLMENTS
INSISHIST.IGV_GENRISKCOVERED
INSISHIST.IGV_GENRISKDISCOUNT
INSISHIST.IGV_POLICY
INSISHIST.IGV_INSUREDOBJECT
INSISHIST.IGV_POLICYRENEWAL
INSISHIST.IGV_PREMINSTINTERIM
INSISHIST.IGV_PREMINSTWP
INSISHIST.IGBV_BLCTRANSACTIONS
INSISHIST.IGBV_BLCPAYMENTS
INSISHIST.ISV_QUESTQUESTIONS
)


CONDITION_ARR=(
INSTALLMENT_ID
POLICY_ID,INSURED_OBJ_ID,COVER_TYPE,ANNEX_ID
DISCOUNT_ID
POLICY_ID
INSURED_OBJ_ID
POLICY_ID,ANNEX_ID,INSR_TYPE
POLICY_ID,ANNEX_ID,INSURED_OBJ_ID,COVER_TYPE,PREM_TYPE
PREM_WP_ID
TRANSACTION_ID
PAYMENT_ID
ID
)

DATE_COL=(
CREATED_ON
REGISTRATION_DATE
UPDATED_ON
REGISTRATION_DATE
REGISTRATION_DATE
REGISTRATION_DATE
UPDATED_ON
REGISTRATION_DATE
TRANSACTION_DATE
CREATED_ON
REGISTRATION_DATE
)

#New loop for 11 tables
# Count of array length
total=${#SOURCE_TAB[*]}


for (( i=0; i<${#SOURCE_TAB[@]}; i++ ))
do
    DB_SCN=$(${ORACLE_HOME}/bin/sqlplus -S "/ as sysdba" <<EOF
set pages 0 feedback off ;
select timestamp_to_scn(SYSTIMESTAMP - 10/24/60) from dual;
exit;
EOF
)

    MIN_DATE=$(${ORACLE_HOME}/bin/sqlplus -S "/ as sysdba" <<EOF
set pages 0 feedback off ;
SELECT TO_CHAR(SYSDATE - 7, 'YYYY-MM-DD') FROM dual;
exit;
EOF
)

    # Build join condition for composite keys
    IFS=',' read -ra KEYS <<< "${CONDITION_ARR[i]}"
    JOIN_COND=""
    SELECT_KEYS=""
    for key in "${KEYS[@]}"; do
      key=$(echo $key | xargs) # trim whitespace
      if [ -n "$JOIN_COND" ]; then
        JOIN_COND="$JOIN_COND AND "
        SELECT_KEYS="$SELECT_KEYS, src.$key"
      else
        SELECT_KEYS="src.$key"
      fi
      JOIN_COND="${JOIN_COND}tgt.$key = src.$key"
    done
    JOIN_COND="$JOIN_COND AND tgt.${DATE_COL[i]} = src.${DATE_COL[i]}"

    Comp_sql="SELECT COUNT(*) FROM (
      SELECT $SELECT_KEYS
      FROM ${SOURCE_TAB[i]} src
      WHERE src.${DATE_COL[i]} >= TO_DATE('$MIN_DATE', 'YYYY-MM-DD')
        AND src.ORA_ROWSCN <= $DB_SCN
        AND NOT EXISTS (
          SELECT 1
          FROM ${TARGET_TAB[i]} tgt
          WHERE $JOIN_COND
        )
    );"

    Count=$(${ORACLE_HOME}/bin/sqlplus -S "/ as sysdba" <<EOF
set pages 0 feedback off ;
$Comp_sql
exit;
EOF
)

    if [ "$Count" -gt 0 ]; then
        echo "${SOURCE_TAB[i]} | ${TARGET_TAB[i]} | $Count" >> ${FILE_DIR}/GG_TAB_Replication.log
        echo "  DEBUG SQL: $Comp_sql" >> ${FILE_DIR}/GG_TAB_Replication.log
        echo "" >> ${FILE_DIR}/GG_TAB_Replication.log
        echo "==================================" >> ${FILE_DIR}/GG_TAB_Replication.log
        echo "" >> ${FILE_DIR}/GG_TAB_Replication.log
    fi

    if [ "$Count" -eq 0 ]; then
        echo "${SOURCE_TAB[i]} | ${TARGET_TAB[i]} | $Count" >> ${FILE_DIR}/GG_TAB_Replication2.log
        echo "DEBUG SQL: $Comp_sql" >> ${FILE_DIR}/GG_TAB_Replication2.log
    fi
done


#Send the email if there is any data difference
if [ `cat $FILE_DIR/GG_TAB_Replication.log|wc -l` -gt 4 ]
then
        #Send the email if there is any data difference
        echo -e "Hi,\n\n Table level data replication from INSIS table to INSISHIST table validation completed successfully. \n Automation script observed the data difference in replication PFA for the log.\n\nThanks & Regards,\nInfosys Infra Automation" | mailx -s "Warning: GoldenGate Replication Validation" -a ${FILE_DIR}/GG_TAB_Replication.log -r GG_Automation@lansforsakringar.se Infosys-Ettsak-Infra-Team@lansforsakringar.se 
fi

if [ `cat $FILE_DIR/GG_TAB_Replication.log|wc -l` -eq 3 ]; then
# Send the info containing all the table compare data
echo -e "Hi,\n\n Table level data replication from INSIS table to INSISHIST table validation completed successfully. \n PFA for the log.\n\nThanks & Regards,\nInfosys Infra Automation" | mailx -s "Info:GoldenGate Replication Validation" -a ${FILE_DIR}/GG_TAB_Replication2.log -r GG_Automation@lansforsakringar.se Konsult.Karthikeyan.Saravanan@lansforsakringar.se
fi
